package game;

	public class NewJFrame extends javax.swing.JFrame {

		/**
		 * Creates new form NewJFrame
		 */
		public NewJFrame() {
		    initComponents();
		}

		/**
		 * This method is called from within the constructor to initialize the form.
		 * WARNING: Do NOT modify this code. The content of this method is always
		 * regenerated by the Form Editor.
		 */
		@SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
		private void initComponents() {

		    jPanel1 = new javax.swing.JPanel();
		    jScrollPane1 = new javax.swing.JScrollPane();
		    chatArea = new javax.swing.JTextArea();
		    jPanel2 = new javax.swing.JPanel();
		    messageArea = new javax.swing.JTextArea();
		    jPanel4 = new javax.swing.JPanel();
		    jScrollPane3 = new javax.swing.JScrollPane();
		    listOnline = new javax.swing.JList<>();
		    buttonDeselect = new javax.swing.JButton();
		    jPanel3 = new javax.swing.JPanel();
		    buttonSend = new javax.swing.JButton();

		    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		    setTitle("SDChat3");
		    setMinimumSize(new java.awt.Dimension(700, 500));

		    jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		    chatArea.setColumns(20);
		    chatArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
		    chatArea.setLineWrap(true);
		    chatArea.setRows(5);
		    chatArea.setMinimumSize(new java.awt.Dimension(500, 300));
		    jScrollPane1.setViewportView(chatArea);

		    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		    jPanel1.setLayout(jPanel1Layout);
		    jPanel1Layout.setHorizontalGroup(
		        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(jScrollPane1)
		    );
		    jPanel1Layout.setVerticalGroup(
		        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(jScrollPane1)
		    );

		    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		    messageArea.setColumns(20);
		    messageArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
		    messageArea.setLineWrap(true);
		    messageArea.setRows(5);

		    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		    jPanel2.setLayout(jPanel2Layout);
		    jPanel2Layout.setHorizontalGroup(
		        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(messageArea)
		    );
		    jPanel2Layout.setVerticalGroup(
		        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(jPanel2Layout.createSequentialGroup()
		            .addGap(0, 0, Short.MAX_VALUE)
		            .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		            .addGap(0, 0, Short.MAX_VALUE))
		    );

		    jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		    listOnline.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		    listOnline.setModel(new javax.swing.AbstractListModel<String>() {
		        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
		        public int getSize() { return strings.length; }
		        public String getElementAt(int i) { return strings[i]; }
		    });
		    jScrollPane3.setViewportView(listOnline);

		    buttonDeselect.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		    buttonDeselect.setText("Deselect");

		    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		    jPanel4.setLayout(jPanel4Layout);
		    jPanel4Layout.setHorizontalGroup(
		        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(jScrollPane3)
		        .addComponent(buttonDeselect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		    );
		    jPanel4Layout.setVerticalGroup(
		        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(jPanel4Layout.createSequentialGroup()
		            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
		            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		            .addComponent(buttonDeselect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
		    );

		    buttonSend.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		    buttonSend.setText("Send");
		    buttonSend.addActionListener(new java.awt.event.ActionListener() {
		        public void actionPerformed(java.awt.event.ActionEvent evt) {
		            buttonSendActionPerformed(evt);
		        }
		    });

		    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		    jPanel3.setLayout(jPanel3Layout);
		    jPanel3Layout.setHorizontalGroup(
		        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
		    );
		    jPanel3Layout.setVerticalGroup(
		        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		    );

		    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		    getContentPane().setLayout(layout);
		    layout.setHorizontalGroup(
		        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
		            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		    );
		    layout.setVerticalGroup(
		        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
		            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		    );

		    pack();
		}// </editor-fold>                        

		private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {                                           
		    // TODO add your handling code here:
		}                                          

		/**
		 * @param args the command line arguments
		 */
		public static void main(String args[]) {
		    /* Set the Nimbus look and feel */
		    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		     */
		    try {
		        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		            if ("Nimbus".equals(info.getName())) {
		                javax.swing.UIManager.setLookAndFeel(info.getClassName());
		                break;
		            }
		        }
		    } catch (ClassNotFoundException ex) {
		        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		    } catch (InstantiationException ex) {
		        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		    } catch (IllegalAccessException ex) {
		        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		    }
		    //</editor-fold>

		    /* Create and display the form */
		    java.awt.EventQueue.invokeLater(new Runnable() {
		        public void run() {
		            new NewJFrame().setVisible(true);
		        }
		    });
		    
		    
		}

		// Variables declaration - do not modify                     
		private javax.swing.JButton buttonDeselect;
		private javax.swing.JButton buttonSend;
		private javax.swing.JTextArea chatArea;
		private javax.swing.JPanel jPanel1;
		private javax.swing.JPanel jPanel2;
		private javax.swing.JPanel jPanel3;
		private javax.swing.JPanel jPanel4;
		private javax.swing.JScrollPane jScrollPane1;
		private javax.swing.JScrollPane jScrollPane3;
		private javax.swing.JList<String> listOnline;
		private javax.swing.JTextArea messageArea;
		// End of variables declaration                   
		}
